# Generated by Django 2.1.2 on 2018-10-16 17:22

from django.db import migrations, models
import teams.teamsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsapp', '0002_auto_20181008_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='members_code',
            field=models.CharField(default=teams.teamsapp.models.generate_code, max_length=15),
        ),
    ]
