# Generated by Django 2.1.2 on 2018-11-02 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsapp', '0003_teams_members_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
