# Generated by Django 2.1.2 on 2018-11-05 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsapp', '0004_auto_20181102_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='equipos', to=settings.AUTH_USER_MODEL),
        ),
    ]
