# Generated by Django 2.1.2 on 2019-04-09 04:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teamsapp', '0005_auto_20181105_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('long', models.FloatField(verbose_name='Longuitud')),
                ('ref', models.CharField(max_length=150, verbose_name='Nombre Checkpoint')),
                ('description', models.TextField(blank=True, null=True)),
                ('kilometer', models.IntegerField(verbose_name='Numero del Kilometro')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Checkpoint Activo?')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Carrera')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descricpion')),
                ('start_hour', models.TimeField(verbose_name='Hora de Inicio')),
                ('kilometers', models.IntegerField(verbose_name='Distancia Total')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Carrera Activa?')),
                ('checkpoints', models.ManyToManyField(related_name='carrera', to='teamsapp.Checkpoint')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
    ]
