# Generated by Django 2.1.2 on 2019-04-09 17:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teamsapp', '0006_checkpoint_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_time', models.DateTimeField()),
                ('penalization', models.IntegerField(default=0)),
                ('total_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='qrcode',
            field=models.ImageField(null=True, upload_to='qrcodes'),
        ),
        migrations.AddField(
            model_name='track',
            name='checkpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamsapp.Checkpoint'),
        ),
        migrations.AddField(
            model_name='track',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamsapp.Teams'),
        ),
    ]
