# Generated by Django 2.1.2 on 2019-04-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsapp', '0009_auto_20190409_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('team', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='teamsapp.Teams')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-total_time', 'checkpoint__num_checkpoint'], 'verbose_name': 'Track', 'verbose_name_plural': 'Tracks'},
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
