# Generated by Django 2.1.2 on 2019-04-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsapp', '0010_auto_20190410_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='¿Es Final?'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='qrcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
