# Generated by Django 2.1.2 on 2019-04-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsapp', '0011_auto_20190411_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
    ]
