# Generated by Django 2.1.2 on 2018-12-05 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teams.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181204_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default=teams.users.models.generate_codes, max_length=250)),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(default=teams.users.models.add_one_day)),
                ('type_code', models.CharField(choices=[('AC', 'Activate'), ('RC', 'Recover')], max_length=50)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Codigo de validacion',
                'verbose_name_plural': 'Codigos de validación',
            },
        ),
    ]
