# Generated by Django 2.1.2 on 2018-12-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='baucher',
            field=models.URLField(blank=True, null=True),
        ),
    ]
